<?php
$config['sender']='info@anglius.ru';
$config['receiver']='info@anglius.ru';
$config['conferences']='conferences';
$config['cache']='0';
$config['redirects']='0';
$config['editable']='0';
$config['dummy']='0';
$config['uploader']='1';
$config['yandex_shopId']='115257';
$config['yandex_scid']='44483';
$config['yandex_customerNumber']='anglius.ru';
$config['yandex_shopPassword']='zVDS5CMnR21E';
$config['yandex_paymethods']='PC,AC,WM,GP,AB,PB,MA';
$config['percent1']='88';
$config['percent2']='74';
$config['percent3']='64';
$config['percent_online1']='69';
$config['percent_online2']='49';
$config['percent_online3']='39';
$config['price91']='100';
$config['price92']='100';
$config['price93']='100';
$config['price94']='100';
?>