<?php
$lang['certificates'] = array(
	'text_form'=>'<div style="line-height: 27px;"> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif"><b>Уважаемые пользователи!</b></font></font></p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">Вы можете заказать:</font></font></p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">- Сертификат об участии в жюри&nbsp;Всероссийского или Международного конкурса, олимпиады,&nbsp;образовательного портала &laquo;Англиус&raquo;;</font></font></p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">- Сертификат выступления на Мастер-классе по указанной Вами теме;</font></font></p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">- Справку-подтверждение результатов участия;</font></font></p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">-&nbsp;Сертификат выступления на вебинаре по указанной Вами теме;</font></font></p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">- Почетная грамота за вклад в развитие специального (коррекционного) образования;</font></font></p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">- Почетная грамота за активную профессиональную разработку сценариев мероприятий и творческий подход;</font></font></p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">- Свидетельство о представлении педагогического опыта;</font></font></p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">- Свидетельство о создании электронного портфолио педагога;</font></font></p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">- Свидетельство участника экспертной комиссии; и.т.д.</font></font></p> 	<p align="center">&nbsp;</p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">Стоимость оформления любого документа 300 рублей.</font></font></p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">Документ выдается в течение 3 рабочих дней с момента оплаты.</font></font></p> 	<p align="center"><font size="3"><font face="Times New Roman, Times, serif">Внимание! Срок хранения сертификатов 120 дней, сохраните копию на своем ПК.</font></font></p> </div> <p>&nbsp;</p>',
	'text_list'=>'Список заявок на сертификаты жюри',
	'price'=>'300',
	'add'=>'Добавить заявку',
	'filltheform'=>'',
	'fio'=>'Фамилия Имя Отчество',
	'workplace'=>'Название учреждения',
	'comment'=>'Укажите вид сертификата (тему) и дату сертификата',
	'send'=>'Отправить',
);?>